name: Deploy to VM

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: your-dockerhub-username/your-app:latest  # Update this

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          HOST: your_vm_ip_address  # Update with your VM IP
          USER: your_vm_user  # Update with your VM username
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/vm_key
          chmod 600 /tmp/vm_key

          ssh -o StrictHostKeyChecking=no -i /tmp/vm_key $USER@$HOST << 'EOF'
            docker pull your-dockerhub-username/your-app:latest
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 80:80 your-dockerhub-username/your-app:latest
          EOF
